Repository coderamp-labs/gitingest, pull requests merged in 2025-07, with the labels that each got.

#338 Fix/windows support
  src/gitingest/utils/git_utils.py
Labels: changes requested

#366 improve UI and backend
  src/server/main.py
  src/server/models.py
  src/server/query_processor.py
  src/server/routers/download.py
  src/server/routers/ingest.py
  src/server/routers_utils.py
  src/server/templates/components/result.jinja
  src/server/templates/swagger_ui.jinja
  src/static/js/git.js
  src/static/js/git_form.js
  src/static/js/utils.js
  tests/test_flow_integration.py
Labels: high priority, backend, frontend

#403 docs: add GitHub Issue Form for bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation, enhancement

#423 ci: add workflow for deploying temporary PR environments
  .github/workflows/deploy-pr.yml
  .github/workflows/docker_image.yml
Labels: deploy-pr-temp-env

#388 refactor: consistent cloning & pattern-handling
  .github/workflows/ci.yml
  .github/workflows/publish_to_pypi.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  pyproject.toml
  src/gitingest/__init__.py
  src/gitingest/clone.py
  src/gitingest/entrypoint.py
  src/gitingest/ingestion.py
  src/gitingest/output_formatter.py
  src/gitingest/query_parser.py
  src/gitingest/schemas/__init__.py
  src/gitingest/schemas/cloning.py
  src/gitingest/schemas/filesystem.py
  src/gitingest/schemas/ingestion.py
  src/gitingest/utils/compat_typing.py
  src/gitingest/utils/exceptions.py
  src/gitingest/utils/git_utils.py
  src/gitingest/utils/ingestion_utils.py
  src/gitingest/utils/os_utils.py
  src/gitingest/utils/path_utils.py
  src/gitingest/utils/pattern_utils.py
  src/gitingest/utils/query_parser_utils.py
  src/server/main.py
  src/server/models.py
  src/server/query_processor.py
  src/server/routers_utils.py
  src/static/llms.txt
  tests/conftest.py
  tests/query_parser/test_git_host_agnostic.py
  tests/query_parser/test_query_parser.py
  tests/server/__init__.py
  tests/server/test_flow_integration.py
  tests/test_clone.py
  tests/test_pattern_utils.py
  tests/test_summary.py
Labels: enhancement

#427 feat: implement S3 integration for storing and retrieving digest files
  .docker/minio/setup.sh
  .env.example
  .pre-commit-config.yaml
  README.md
  compose.yml
  pyproject.toml
  requirements.txt
  src/gitingest/query_parser.py
  src/gitingest/schemas/ingestion.py
  src/server/models.py
  src/server/query_processor.py
  src/server/routers/ingest.py
  src/server/s3_utils.py
  src/static/js/utils.js
  tests/conftest.py
  tests/query_parser/test_git_host_agnostic.py
  tests/server/test_flow_integration.py
Labels: deploy-pr-temp-env

#462 feat: serve cached digest if available
  .github/workflows/ci.yml
  src/server/models.py
  src/server/query_processor.py
  src/server/s3_utils.py
Labels: push-container, deploy-pr-temp-env

#473 feat(logging): implement loguru
  .github/workflows/deploy-pr.yml
  .pre-commit-config.yaml
  .vscode/launch.json
  CONTRIBUTING.md
  Dockerfile
  compose.yml
  pyproject.toml
  requirements.txt
  src/gitingest/__main__.py
  src/gitingest/clone.py
  src/gitingest/entrypoint.py
  src/gitingest/ingestion.py
  src/gitingest/output_formatter.py
  src/gitingest/query_parser.py
  src/gitingest/utils/git_utils.py
  src/gitingest/utils/logging_config.py
  src/gitingest/utils/notebook.py
  src/gitingest/utils/query_parser_utils.py
  src/server/__main__.py
  src/server/main.py
  src/server/metrics_server.py
  src/server/query_processor.py
  src/server/s3_utils.py
  src/server/server_utils.py
  tests/server/test_flow_integration.py
  tests/test_notebook_utils.py
Labels: deploy-pr-temp-env

#477 fix: improved server side cleanup after ingest
  src/server/main.py
  src/server/query_processor.py
  src/server/server_config.py
  src/server/server_utils.py
Labels: deploy-pr-temp-env
